name: Makefile CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:

  setup:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v3
      - run: bash -x ./ci/build.sh
      - run: make test

