name: Makefile CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:

  setup:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v3
      # Check if GitHub Cache has it, because that's free
      - name: Using the builtin GitHub Cache Action for .conan
        id: github-cache-conan
        uses: actions/cache@v1
        env:
          cache-name: cache-conan-modules
        with:
          path: ~/.conan/
          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ hashFiles('conanfile.py') }}
      - run: bash -x ./ci/build.sh
      - run: make test

