name: Makefile CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'libs'
          - 'test'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
        fallback-style: 'Mozilla' # optional

  setup:
    runs-on: ubuntu-latest
    name: build & test
    needs: [ formatting-check ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v3
      # Check if GitHub Cache has it, because that's free
      - name: Using the builtin GitHub Cache Action for .conan
        id: github-cache-conan
        uses: actions/cache@v1
        env:
          cache-name: cache-conan-modules
        with:
          path: ~/.conan/
          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ hashFiles('conanfile.py') }}
      - run: bash -x ./ci/build.sh
      - run: make test

